# permissions for end users to edit appoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appoperator-editor-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - appoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - appoperators/status
  verbs:
  - get
