# permissions for end users to view appoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appoperator-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - appoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - appoperators/status
  verbs:
  - get
